//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLXuatNhapKhoLKDT.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\SONSQLSERVER;Initial Catalog=QL_XUATNHAPKHO_LKDT;Integrated Securit" +
            "y=True")]
        public string QL_XUATNHAPKHO_LKDTConnectionString {
            get {
                return ((string)(this["QL_XUATNHAPKHO_LKDTConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=lightingwindows.vnso.vn\\MSSQLSERVER2014;Initial Catalog=ytnpjqvx_QL_X" +
            "OSO_VIETLOTT;User ID=quanlyxosovietlott;Password=Ahng89di@@2")]
        public string ytnpjqvx_QL_XOSO_VIETLOTTConnectionString {
            get {
                return ((string)(this["ytnpjqvx_QL_XOSO_VIETLOTTConnectionString"]));
            }
        }
    }
}
